#!/usr/bin/env python3
r"""io_guard_go.py -- the tier-aware runtime I/O guard for test-safety-net, Go.

This is the SOLE enforcement of the skill's headline invariant, "never writes
a test that performs real I/O", on the Go stack. `stack_go.py`'s triage is a
FILTER: interface dispatch, function values and reflection make reachability
undecidable from source, so the invariant is a RUNTIME property or nothing.

DOCUMENTED COMMAND -- copy the whole block. The tier travels by environment
variable, the same contract `io_guard.py` and `io_guard.js` read, and nothing
is written into the target repo, so Invariant 1 holds with no carve-out:

    TEST_SAFETY_NET_TIER=1 \
      python3 "$SKILL_DIR/assets/io_guard_go.py" \
      -run '^<test_name>$' <package>

    TEST_SAFETY_NET_TIER=2 TEST_SAFETY_NET_ALLOW=filesystem,clock \
      python3 "$SKILL_DIR/assets/io_guard_go.py" \
      -run '^<test_name>$' <package>

Everything after the script name is handed to `go test` unchanged, except
that `-count` is forced to 1 and `-overlay` is refused (both below).
`assets/test_io_guard_go.py` extracts those two commands from this header and
from every markdown file in the skill and runs them verbatim, in both
directions, so what is printed here is what is proved to work.

THE EXIT STATUS IS THE WHOLE PROTOCOL
-------------------------------------
    0  GREEN        the selected test ran and passed
    1  RED          the selected test ran and failed an assertion
    2  NOT ARMED    the guard could not arm; NOTHING was proved
    3  GUARD TRIP   IOGuardViolation: the CLASSIFICATION is wrong --
                    reclassify the unit to Tier 3 and discard the test,
                    whether the run was red or green
    4  NO TEST      nothing was proved: `-run` matched nothing, the package
                    has no test files, or the test skipped itself
    5  NO BUILD     the package did not build; a compile error is not RED

Node had to learn that per-test lines lie about asynchronous violations. Here
there is nothing to misread: a trip ENDS THE PROCESS.

HOW IT WORKS
------------
`go test` compiles before it runs, so there is no live object graph to patch
the way the python and node guards patch theirs. What there is instead is
`-overlay`: a JSON map that replaces source files in the build without
touching them on disk -- the standard library's included. So every run:

  1. lists this toolchain's own sources (`go list -e -json`), so the choice
     of per-GOOS/GOARCH files is Go's, not a table's;
  2. injects one line at the top of each I/O primitive -- every classified
     `syscall` function, the `internal/syscall/unix` *at and resolver
     families, `time`'s clock entry points, the global `math/rand` sources,
     `crypto/internal/sysrand`, `database/sql.Open`, and the `net`,
     `net/http` and `crypto/tls` entry points;
  3. adds the decision engine to package `syscall`, and a one-line forwarder
     to every other hooked package;
  4. runs `go test -overlay <map> -count=1 -vet=off -v ...`. `-vet=off`
     because `go vet` on Go 1.22-1.23 does not honour an overlay's ADDED
     files and failed every run there; vet is a lint, not part of a proof.
     `-v` because GREEN needs a `--- PASS:` line to point at.

A cold build of the overlaid standard library took 5s on go 1.26.7; a warm
one 0s -- the build cache keys on content, not path, so the overlay can live
in a fresh temporary directory every run. Tier and allow reach the engine by
environment, never baked into the source, so every tier shares one build.

THE DECISION RULE -- CALL PROVENANCE, AS IN io_guard.js
------------------------------------------------------
A hook fires on every call, including the standard library's calls on its
own behalf -- `testing` reads the clock around every test. The engine walks
`runtime.Callers` from the innermost frame outward:

  * a standard-library frame is TRANSPARENT (`go list std`, baked in); the
    walk remembers the last one it passed -- the ENTRY, the function the
    code under test actually called;
  * a frame in package `main` whose file is `_testmain.go` is the runner
    `go test` generates: EXEMPT. BELT-AND-BRACES, measured: every hooked
    call `main.main` makes today passes through `testing.(*M).Run` first,
    which the next rule already exempts, so removing this line alone leaves
    the suite green and only removing both turns the clean test red. It
    stays because the file is generated by `go test`, not by this skill, and
    a release that reached a hook from `main.main` through
    `testing/internal/testdeps` -- std, but not `testing` -- would pass
    through no rule but this one;
  * a frame in package `testing` that is NOT one of its controls means the
    runner is doing its OWN work on the test's behalf -- reporting a
    failure, timing a test -- and the call is EXEMPT. This is what measured
    into existence: `t.Fatal` reaches `runtime.Goexit`, which runs
    `tRunner`'s deferred `time.Since` with `Fatal <- TestX` still beneath
    it, so without this every RED run of the proof loop tripped as `clock`.
    What it cannot exempt is repo code: a repo `defer` doing I/O during a
    panic, a `t.Cleanup` closure and a subtest body all put a repo frame
    INNERMOST, before any testing frame is reached;
  * the first other frame -- the repo's code, or a third-party module, which
    is treated as the repo's the way io_guard.js treats node_modules -- is
    ATTRIBUTABLE, and the call is judged there;
  * reaching the end of the stack means THIS GOROUTINE holds no repo frame,
    and it is judged by the function that CREATED it -- the "created by"
    line `runtime.Stack` appends. A stdlib or generated-runner creator is the
    runtime doing its own work: EXEMPT. Any other creator is ATTRIBUTABLE.
    Review forced this: the rule used to exempt every such stack, and
    `go http.ListenAndServe(...)` in a unit bound a real port under a GREEN
    proof, because the compiler's wrapper for a `go` statement is hidden
    from runtime.Callers and the goroutine's stack is all stdlib;
  * the walk reads the WHOLE stack, growing its buffer as it goes. A fixed
    64-frame buffer read its cut-off tail as "end of stack" and exempted a
    40-level recursive template reading the environment.

Provenance reads a frame's PACKAGE PATH (`runtime.Frame.Function`), never
its file path, which `-trimpath` rewrites.

A call is blocked when the primitive's group is blocked, OR the entry's.
`net.Dial` reads the clock before it opens a socket; judged by the primitive
alone, a dial trips as `clock` -- and at tier 2 with clock allowed it would
trip later, at the socket, correctly but for the wrong reason at the wrong
moment. The entry says `network`. Testing CONTROLS override rather than add:
`t.TempDir()` reads TMPDIR on its way to the filesystem, and is the tier-2
filesystem control, so an entry of `testing.(*common).TempDir` means
filesystem alone.

A trip writes `IOGuardViolation: ...` to fd 2 and calls `syscall.Exit(3)`.
That is not a panic, so `recover()` cannot swallow it, and it ends the
process from any goroutine -- the two properties the python guard needed a
BaseException subclass and a thread hook to approximate, and the node guard
an exit-time backstop.

RESIDUALS, STATED RATHER THAN IMPLIED
-------------------------------------
1. Anything that bypasses package `syscall` is unseen: a raw syscall through
   `golang.org/x/sys/unix`, cgo, assembly. The filter declines the raw and
   cgo shapes statically; a third-party library doing it internally escapes
   both layers.
2. Standard-library work on a goroutine the standard library started ITSELF
   -- whose creator is stdlib, and whose stack holds no repo frame -- is
   exempt. A goroutine the UNIT started is judged by its creator, so
   `go http.ListenAndServe(...)` trips; what stays open is, say, the
   per-connection goroutines a stdlib server spawns. The `net/http` entry
   points are hooked on the caller's goroutine for the case that matters.
   A dependency's import-time I/O trips too, and is reported as the
   dependency's, not as a verdict on the unit.
3. Hook targets are found by text in THIS toolchain's sources. A release that
   renames a required one makes this exit 2; an optional one missing is
   recorded, not fatal.
4. `time.Sleep` has no Go body (it is linknamed to the runtime), so it is not
   hooked; a unit that only sleeps passes tier 1. `os.Args` is a variable the
   runtime fills before `main`, so reading it calls nothing a hook could sit
   in. The filter marks both; the guard sees neither.
5. Map iteration order, `select` choice and goroutine scheduling are
   nondeterminism no hook can see. A characterization test must not pin them.
6. darwin and linux only. Anything else exits 2 rather than running unarmed.
"""
from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import sys
import tempfile

_ASSETS = os.path.dirname(os.path.abspath(__file__))
if _ASSETS not in sys.path:
    sys.path.insert(0, _ASSETS)

import stack_go                                                     # noqa: E402
from stack_go import SYSCALL_GROUPS                                 # noqa: E402

TIER_ENV = "TEST_SAFETY_NET_TIER"
ALLOW_ENV = "TEST_SAFETY_NET_ALLOW"

# The groups are the FILTER's, verbatim -- one answer to "what counts as
# which I/O", owned by `stack_go.py`. `randomness` is uncontrollable on Go,
# so the allow list can never permit it.
GROUPS = stack_go.GROUPS
CONTROLLABLE_GROUPS = tuple(sorted(stack_go.CONTROLLABLE))
UNCONTROLLABLE_GROUPS = tuple(sorted(stack_go.UNCONTROLLABLE))

EXIT_GREEN, EXIT_RED, EXIT_NOT_ARMED, EXIT_TRIP, EXIT_NO_TEST, EXIT_NO_BUILD = 0, 1, 2, 3, 4, 5

SUPPORTED_GOOS = ("darwin", "linux")

_PREFIX = "test-safety-net io_guard_go: "


class GuardCannotArm(Exception):
    """The overlay cannot be built on this toolchain. Nothing may run."""


# ── Environment -> tier ──────────────────────────────────────────────────

def read_env(env):
    """`(tier, allow, notes)`. Never raises.

    The contract `io_guard.py`'s `read_env` and `io_guard.js`'s `readEnv`
    share: an absent or invalid tier is tier 1 -- the fail-safe direction --
    with a note; `none` allows nothing; an unknown group is ignored and stays
    blocked; tier 1 ignores the allow list. One addition, because Go's
    controllable set is smaller: naming `randomness` says why it stays
    blocked instead of calling it unknown.
    """
    notes = []
    raw = str(env.get(TIER_ENV, "")).strip()
    if raw in ("1", "2"):
        tier = int(raw)
    else:
        tier = 1
        notes.append("%s=%r is not 1 or 2; defaulting to tier 1 (block everything), "
                     "the fail-safe direction" % (TIER_ENV, raw))
    raw_allow = env.get(ALLOW_ENV)
    if raw_allow is None or not str(raw_allow).strip():
        allow = None
    elif str(raw_allow).strip().lower() == "none":
        allow = []
    else:
        wanted = [g.strip() for g in re.split(r"[,;]", str(raw_allow)) if g.strip()]
        allow = [g for g in wanted if g in CONTROLLABLE_GROUPS]
        for g in wanted:
            if g in CONTROLLABLE_GROUPS:
                continue
            if g in UNCONTROLLABLE_GROUPS:
                why = ("rand.Seed is a no-op since Go 1.24, so no test can seed the "
                       "global source" if g == "randomness" else "no test can control it")
                notes.append("%s names %s, which is not controllable on go (%s); it stays "
                             "blocked" % (ALLOW_ENV, g, why))
            else:
                notes.append("%s names unknown group %r; it is ignored and stays blocked"
                             % (ALLOW_ENV, g))
    if tier == 1 and allow:
        notes.append("tier 1 ignores %s: a unit that claimed to touch nothing gets "
                     "everything blocked" % ALLOW_ENV)
    return tier, allow, notes


def blocked_groups(tier, allow):
    """The groups a run at `tier` blocks. Tier 1: all. Tier 2: all but what it fakes."""
    if tier == 1:
        return set(GROUPS)
    if allow is None:
        return set(UNCONTROLLABLE_GROUPS)
    permitted = {g for g in allow if g in CONTROLLABLE_GROUPS}
    return set(GROUPS) - permitted


# ── What gets a hook ─────────────────────────────────────────────────────

def syscall_targets():
    """Every `syscall` name the filter classifies into a group, plus `Read` (stdin)."""
    return {n for n, g in SYSCALL_GROUPS.items() if g in GROUPS or g == "stdin"}


def _names(spec):
    return spec.split()


_UNIX_TARGETS = {
    "filesystem": "Openat Unlinkat Fstatat Mkdirat Linkat Symlinkat Readlinkat Renameat "
                  "Fchmodat Fchownat Utimensat Eaccess",
    "network": "Getaddrinfo Getnameinfo ResNsearch ResNinit SendtoInet4 SendtoInet6 "
               "SendmsgNInet4 SendmsgNInet6 RecvfromInet4 RecvfromInet6 RecvmsgInet4 "
               "RecvmsgInet6",
    "randomness": "GetRandom ARC4Random",
    "subprocess": "PidFDOpen PidFDSendSignal Waitid",
    "environment": "Getpwnam Getpwuid Getgrnam Getgrgid Getgrouplist Sysconf KernelVersion",
}


def _top_level(pkg, table_group):
    """The top-level function names the filter marks under `pkg.`."""
    prefix = pkg + "."
    return [m[len(prefix):] for m in stack_go.UNCONTROLLABLE.get(table_group, ())
            + stack_go.CONTROLLABLE.get(table_group, ())
            if m.startswith(prefix) and "." not in m[len(prefix):]]


def _hook_targets():
    """[(package path, receiver type or None, name, group)], deduplicated, ordered."""
    t = [("syscall", None, n, SYSCALL_GROUPS[n]) for n in sorted(syscall_targets())]
    for group, spec in _UNIX_TARGETS.items():
        t += [("internal/syscall/unix", None, n, group) for n in _names(spec)]
    t += [("time", None, n, "clock") for n in _names(
        "Now Since Until After AfterFunc NewTimer NewTicker Tick Sleep")]
    t += [("math/rand", None, n, "randomness") for n in _top_level("math/rand", "randomness")]
    t += [("math/rand/v2", None, n, "randomness")
          for n in _top_level("math/rand/v2", "randomness")]
    t += [("crypto/rand", None, n, "randomness") for n in _names("Int Prime Read Text")]
    t += [("crypto/internal/sysrand", None, "Read", "randomness")]
    t += [("database/sql", None, n, "database") for n in _names("Open OpenDB")]
    t += [("net", None, n, "network") for n in _names(
        "Dial DialIP DialTCP DialTimeout DialUDP DialUnix FileConn FileListener "
        "FilePacketConn InterfaceAddrs InterfaceByIndex InterfaceByName Interfaces Listen "
        "ListenIP ListenMulticastUDP ListenPacket ListenTCP ListenUDP ListenUnix "
        "ListenUnixgram LookupAddr LookupCNAME LookupHost LookupIP LookupMX LookupNS "
        "LookupPort LookupSRV LookupTXT")]
    t += [("net", "Dialer", n, "network") for n in _names(
        "Dial DialContext DialIP DialTCP DialUDP DialUnix")]
    t += [("net", "Resolver", n, "network") for n in _names(
        "LookupAddr LookupCNAME LookupHost LookupIP LookupIPAddr LookupMX LookupNS "
        "LookupNetIP LookupPort LookupSRV LookupTXT")]
    t += [("net", "ListenConfig", n, "network") for n in _names("Listen ListenPacket")]
    t += [("net/http", None, n, "network") for n in _names(
        "Get Head Post PostForm ListenAndServe ListenAndServeTLS Serve ServeTLS")]
    t += [("net/http", "Client", "Do", "network"),
          ("net/http", "Transport", "RoundTrip", "network")]
    t += [("crypto/tls", None, n, "network") for n in _names("Dial DialWithDialer Listen")]
    seen, out = set(), []
    for item in t:
        key = item[:3]
        if key not in seen:
            seen.add(key)
            out.append(item)
    return out


HOOK_TARGETS = _hook_targets()

# One per group, plus stdin: the targets whose absence leaves a WHOLE GROUP
# unguarded. Missing any of them, the guard refuses to run (exit 2) -- a proof
# that ran with a group silently open is worse than no proof.
REQUIRED_TARGETS = frozenset({
    ("syscall", None, "Open"), ("syscall", None, "Socket"), ("syscall", None, "ForkExec"),
    ("syscall", None, "Getenv"), ("syscall", None, "Read"), ("time", None, "Now"),
    ("math/rand/v2", None, "IntN"), ("database/sql", None, "Open"),
})

# The standard-library entry points whose GROUP decides a call made beneath
# them, whatever primitive it reaches first (see "THE DECISION RULE").
ENTRY_GROUPS = (
    ("net/http.", "network"), ("net/rpc.", "network"), ("net/smtp.", "network"),
    ("crypto/tls.", "network"), ("net.", "network"),
    ("os/exec.", "subprocess"), ("os.StartProcess", "subprocess"),
    ("os.FindProcess", "subprocess"), ("os.(*Process)", "subprocess"),
    ("database/sql.", "database"),
    ("time.", "clock"),
    ("math/rand/v2.", "randomness"), ("math/rand.", "randomness"),
    ("crypto/rand.", "randomness"),
    ("os.Getenv", "environment"), ("os.LookupEnv", "environment"),
    ("os.Environ", "environment"), ("os.Setenv", "environment"),
    ("os.Unsetenv", "environment"), ("os.Clearenv", "environment"),
    ("os.ExpandEnv", "environment"), ("os.Hostname", "environment"),
    ("os.TempDir", "environment"), ("os.UserHomeDir", "environment"),
    ("os.UserCacheDir", "environment"), ("os.UserConfigDir", "environment"),
)

# The testing package's own CONTROLS: an entry of one of these means exactly
# these groups, whatever the call reaches beneath. `t.TempDir()` reads TMPDIR
# on its way to creating a directory -- and is the tier-2 filesystem control.
# The `(*T)`/`(*B)`/`(*F)` spellings are the promoted-method wrappers the
# compiler generates; which one a frame shows depends on inlining.
TESTING_CONTROL_METHODS = {
    "TempDir": "filesystem",
    "ArtifactDir": "filesystem",
    "Setenv": "environment",
    "Chdir": "filesystem,environment",
}
TESTING_CONTROLS = {"testing.(*%s).%s" % (recv, method): groups
                    for recv in ("common", "T", "B", "F")
                    for method, groups in TESTING_CONTROL_METHODS.items()}

# Every OTHER exported method of testing's T, B and F, and why a call beneath
# it is the runner's own work. This list is load-bearing in the permissive
# direction, which is why it is spelled out: a `testing` frame that is not a
# control EXEMPTS the call (see the engine), so a helper that did I/O for the
# test and was missing from `TESTING_CONTROL_METHODS` would be silently
# exempt. `test_io_guard_go.py` derives the method set from `go doc testing`
# and fails on any name in neither table -- a Go release that adds a testing
# helper has to be classified here before this suite goes green again.
_REPORTING = "records or reports an outcome -- the runner's own bookkeeping"
_BENCH = "benchmark bookkeeping; the clock it reads is the runner's, not the unit's"
TESTING_NO_IO = {
    "Attr": "records a key/value pair in the test's own output",
    "Cleanup": "registers a function; when it runs, its own frame is innermost and is "
               "judged there like any other repo code",
    "Context": "returns a context; no I/O",
    "Deadline": "reports the -timeout deadline the runner computed",
    "Elapsed": _BENCH,
    "Error": _REPORTING, "Errorf": _REPORTING, "Fail": _REPORTING, "Failed": _REPORTING,
    "FailNow": _REPORTING, "Fatal": _REPORTING, "Fatalf": _REPORTING,
    "Skip": _REPORTING, "Skipf": _REPORTING, "SkipNow": _REPORTING, "Skipped": _REPORTING,
    "Helper": "marks its caller as a helper for line reporting",
    "Log": "writes to the test's own log", "Logf": "writes to the test's own log",
    "Output": "returns a writer onto the test's own log",
    "Name": "returns the test's name",
    "Parallel": "schedules the test",
    "Run": "starts a subtest, whose body runs on its own goroutine with its own frame "
           "innermost",
    "RunParallel": "runs the benchmark body on goroutines whose innermost frame is the body",
    "Loop": _BENCH, "ReportAllocs": _BENCH, "ReportMetric": _BENCH, "ResetTimer": _BENCH,
    "SetBytes": _BENCH, "SetParallelism": _BENCH, "StartTimer": _BENCH, "StopTimer": _BENCH,
    "Add": "adds a seed-corpus entry, in memory",
    "Fuzz": "runs the fuzz target over its seed corpus; reading testdata/fuzz is the runner "
            "loading the test's own fixtures, as it loads the test file",
}


# ── The filter <-> guard correspondence ──────────────────────────────────
#
# `stack_go.py`'s marker tables are what the FILTER declines on; these three
# maps are what this guard does about each marker. `test_io_guard_go.py`
# asserts they PARTITION those tables -- every marker in exactly one, with a
# reason -- so a marker added to the filter with nothing said here fails the
# gate instead of opening a silent two-layer hole.

_FS = ("the syscall filesystem primitives (Open, Stat, Mkdir, Unlink, Rename, ...) "
       "and internal/syscall/unix's *at family, which every os path function "
       "bottoms out in")
_ENV = "syscall.Getenv / Environ / Setenv / Unsetenv / Clearenv"
_ID = "syscall's process-identity family (Getpid, Getuid, Getgroups, ...), environment group"
_NET_BENEATH = ("syscall.Socket / Connect / Bind / Listen / Sendto / Recvfrom beneath, "
                "and internal/syscall/unix's resolver entry points")
_RAND_ENTRY = "hooked at its own entry"
_DRIVER = ("net or the filesystem beneath: a pure-Go driver dials through net or opens its "
           "file through syscall, both hooked")

FILTER_MARKER_INTERCEPTS = {}
FILTER_MARKER_INTERCEPTS.update(dict.fromkeys((
    "os.Open", "os.OpenFile", "os.Create", "os.ReadFile", "os.WriteFile", "os.ReadDir",
    "os.Stat", "os.Lstat", "os.Mkdir", "os.MkdirAll", "os.MkdirTemp", "os.CreateTemp",
    "os.Remove", "os.RemoveAll", "os.Rename", "os.Link", "os.Symlink", "os.Readlink",
    "os.Chmod", "os.Chown", "os.Lchown", "os.Chtimes", "os.Truncate", "os.DirFS",
    "os.CopyFS", "os.OpenRoot", "os.OpenInRoot", "os.Getwd", "os.Chdir",
    "io/ioutil.ReadFile", "io/ioutil.WriteFile", "io/ioutil.ReadDir", "io/ioutil.TempDir",
    "io/ioutil.TempFile", "path/filepath.Walk", "path/filepath.WalkDir",
    "path/filepath.Glob", "path/filepath.EvalSymlinks", "path/filepath.Abs"), _FS))
FILTER_MARKER_INTERCEPTS["time.LoadLocation"] = "syscall.Open, reading the zoneinfo database"
FILTER_MARKER_INTERCEPTS.update({"time." + n: "time.%s, hooked at its entry" % n for n in _names(
    "Now Since Until After AfterFunc NewTimer NewTicker Tick")})
FILTER_MARKER_INTERCEPTS.update(dict.fromkeys((
    "os.Getenv", "os.LookupEnv", "os.Environ", "os.Setenv", "os.Unsetenv", "os.Clearenv",
    "os.ExpandEnv", "os.TempDir", "os.UserHomeDir", "os.UserCacheDir", "os.UserConfigDir"),
    _ENV))
FILTER_MARKER_INTERCEPTS.update(dict.fromkeys((
    "os.Getpid", "os.Getppid", "os.Getuid", "os.Geteuid", "os.Getgid", "os.Getegid",
    "os.Getgroups"), _ID))
FILTER_MARKER_INTERCEPTS["os.Hostname"] = "syscall.Sysctl (darwin) / syscall.Uname (linux)"
FILTER_MARKER_INTERCEPTS["os.Executable"] = ("syscall.Sysctl on darwin; a readlink of "
                                             "/proc/self/exe on linux (filesystem)")
FILTER_MARKER_INTERCEPTS.update(dict.fromkeys(
    [m for m in stack_go.UNCONTROLLABLE["randomness"]
     if m.startswith(("math/rand.", "math/rand/v2."))], _RAND_ENTRY))
FILTER_MARKER_INTERCEPTS["crypto/rand"] = ("crypto/rand.Read / Int / Prime / Text at entry, "
                                           "and crypto/internal/sysrand.Read beneath them")
FILTER_MARKER_INTERCEPTS.update({"net." + n: "net.%s at its entry; %s" % (n, _NET_BENEATH)
                                 for n in _names(
    "Dial DialIP DialTCP DialTimeout DialUDP DialUnix FileConn FileListener FilePacketConn "
    "InterfaceAddrs InterfaceByIndex InterfaceByName Interfaces Listen ListenIP "
    "ListenMulticastUDP ListenPacket ListenTCP ListenUDP ListenUnix ListenUnixgram "
    "LookupAddr LookupCNAME LookupHost LookupIP LookupMX LookupNS LookupPort LookupSRV "
    "LookupTXT")})
FILTER_MARKER_INTERCEPTS["net.Dialer"] = "its Dial* methods, hooked at entry; " + _NET_BENEATH
FILTER_MARKER_INTERCEPTS["net.Resolver"] = "its Lookup* methods, hooked at entry"
FILTER_MARKER_INTERCEPTS["net.ListenConfig"] = "its Listen / ListenPacket methods, hooked at entry"
FILTER_MARKER_INTERCEPTS.update(dict.fromkeys((
    "net/http.Get", "net/http.Head", "net/http.Post", "net/http.PostForm",
    "net/http.ListenAndServe", "net/http.ListenAndServeTLS", "net/http.Serve",
    "net/http.ServeTLS"), "net/http, hooked at its entry; net beneath"))
FILTER_MARKER_INTERCEPTS["net/http.Server"] = (
    "(*Server).ListenAndServe / Serve reach net.Listen, hooked -- and a "
    "`go srv.ListenAndServe()` goroutine, whose stack holds no repo frame, is "
    "judged by the unit that created it")
FILTER_MARKER_INTERCEPTS["net/http.Transport"] = "(*Transport).RoundTrip, hooked at entry"
FILTER_MARKER_INTERCEPTS.update(dict.fromkeys((
    "net/http.DefaultClient", "net/http.Client"),
    "(*Client).Do and (*Transport).RoundTrip, hooked on the CALLER's goroutine -- the dial "
    "itself runs on one the transport starts, with no repo frame on it"))
FILTER_MARKER_INTERCEPTS.update(dict.fromkeys(("net/rpc", "net/smtp", "google.golang.org/grpc"),
                                              "net beneath: no transport of its own"))
FILTER_MARKER_INTERCEPTS.update(dict.fromkeys((
    "crypto/tls.Dial", "crypto/tls.DialWithDialer", "crypto/tls.Listen"),
    "crypto/tls, hooked at its entry; net beneath"))
FILTER_MARKER_INTERCEPTS["os/exec"] = ("syscall.ForkExec / StartProcess beneath exec.Cmd.Start, "
                                       "and syscall.Stat beneath LookPath")
FILTER_MARKER_INTERCEPTS["os.StartProcess"] = "syscall.StartProcess"
FILTER_MARKER_INTERCEPTS.update(dict.fromkeys(("database/sql.Open", "database/sql.OpenDB"),
                                              "database/sql, hooked at its entry"))
FILTER_MARKER_INTERCEPTS.update(dict.fromkeys((
    "github.com/jackc/pgx", "github.com/lib/pq", "go.mongodb.org/mongo-driver",
    "github.com/redis/go-redis", "github.com/go-redis/redis", "gorm.io/gorm",
    "github.com/jmoiron/sqlx", "modernc.org/sqlite", "go.etcd.io/bbolt",
    "github.com/dgraph-io/badger"), _DRIVER))

PARTIALLY_INTERCEPTED = {
    "os.FindProcess": "on linux it opens a pidfd (internal/syscall/unix.PidFDOpen, hooked); on "
                      "darwin it returns a handle without a syscall, and the Signal / Kill that "
                      "follow are syscall.Kill, hooked",
    "github.com/mattn/go-sqlite3": "a cgo driver: its file I/O happens in C, which no Go hook "
                                   "sees. database/sql.Open, which any use goes through, is "
                                   "hooked -- and the filter declines cgo statically",
}

NOT_INTERCEPTED = {
    "time.Sleep": "no Go body -- it is linknamed to the runtime -- so there is nowhere to inject "
                  "a hook; a unit that only sleeps passes tier 1",
    "os.Args": "a package variable the runtime fills before main; reading it calls nothing a "
               "hook could sit in",
    "os.Getpagesize": "syscall.Getpagesize has no Go body (runtime linkname); it reports a "
                      "machine constant rather than performing I/O",
    "hash/maphash.MakeSeed": "seeded from the runtime's own random source (runtime.rand), which "
                             "has no Go function a hook could sit in",
    "plugin.Open": "loads a shared object through the dynamic linker, via cgo; nothing a Go hook "
                   "sees -- and a cgo build is exactly what the filter declines",
}


# ── Injection ────────────────────────────────────────────────────────────

def _decl_re(name, recv):
    if recv is None:
        return re.compile(r"(?m)^func[ \t]+%s(?![A-Za-z0-9_])" % re.escape(name))
    return re.compile(r"(?m)^func[ \t]*\([ \t]*(?:[A-Za-z_][A-Za-z0-9_]*[ \t]+)?\*?[ \t]*%s"
                      r"(?:\[[^\]]*\])?[ \t]*\)[ \t]*%s(?![A-Za-z0-9_])"
                      % (re.escape(recv), re.escape(name)))


def _body_brace(code, depths, pos):
    """Index of the `{` opening the body of the declaration at `pos`, or None.

    The first brace at `pos`'s depth that is not an `interface{...}` or
    `struct{...}` result type, before the newline that ends a bodyless
    declaration.
    """
    n = len(code)
    d0 = depths[pos]
    i = pos
    while i < n:
        c = code[i]
        if depths[i] < d0:
            return None
        if depths[i] == d0 and c == "\n":
            return None
        if depths[i] == d0 and c == "{":
            k = i - 1
            while k >= 0 and code[k].isspace():
                k -= 1
            end = k + 1
            while k >= 0 and (code[k].isalnum() or code[k] == "_"):
                k -= 1
            if code[k + 1:end] in ("interface", "struct"):
                close = stack_go._match_bracket(code, depths, i)
                if close < 0:
                    return None
                i = close + 1
                continue
            return i
        i += 1
    return None


def inject(source, name, stmt, recv=None):
    """`source` with `stmt` as the first statement of `name`'s body.

    Raises KeyError when the declaration is not there at all; returns None
    when it is there with NO BODY (assembly, or a runtime linkname) -- the
    caller records that rather than fails. Positions are found on the
    comment- and string-stripped copy, which preserves every offset, so a
    brace inside a comment or a string can never be taken for the body.
    """
    code = stack_go.strip_noncode(source)
    m = _decl_re(name, recv).search(code)
    if not m:
        raise KeyError(name if recv is None else "%s.%s" % (recv, name))
    depths = stack_go._depths(code)
    brace = _body_brace(code, depths, m.start())
    if brace is None:
        return None
    after = source[brace + 1:brace + 2]
    return source[:brace + 1] + "\n\t" + stmt + ("" if after == "\n" else "\n") + source[brace + 1:]


# ── The engine ───────────────────────────────────────────────────────────
#
# Go source, formatted per run with the toolchain's own `go list std`. It lives
# in package `syscall` because that is the one package every hooked package can
# import without a cycle, and it imports only `runtime` and `sync` -- anything
# more is a cycle waiting for a Go release to close it. It reads its
# configuration through `runtime_envs()`, never through `Getenv`, which is
# hooked and would recurse.

_ENGINE = r'''// Code generated by test-safety-net io_guard_go.py for one proof run. DO NOT EDIT.

package syscall

import (
	"runtime"
	"sync"
)

var tsnState struct {
	once    sync.Once
	armed   bool
	tier    string
	blocked map[string]bool
	stdin   bool
	modules []string
}

var tsnStd = [...]string{__STD__}

var tsnEntryGroups = [...][2]string{__ENTRY__}

var tsnControls = map[string]string{__CONTROLS__}

func tsnEnv(key string) (string, bool) {
	for _, kv := range runtime_envs() {
		if len(kv) > len(key) && kv[len(key)] == '=' && kv[:len(key)] == key {
			return kv[len(key)+1:], true
		}
	}
	return "", false
}

func tsnSplit(s string) []string {
	var out []string
	start := 0
	for i := 0; i <= len(s); i++ {
		if i == len(s) || s[i] == ',' {
			if i > start {
				out = append(out, s[start:i])
			}
			start = i + 1
		}
	}
	return out
}

func tsnArm() {
	blocked, ok := tsnEnv("TEST_SAFETY_NET_GO_BLOCKED")
	if !ok {
		return
	}
	tsnState.blocked = map[string]bool{}
	for _, g := range tsnSplit(blocked) {
		tsnState.blocked[g] = true
	}
	s, _ := tsnEnv("TEST_SAFETY_NET_GO_STDIN")
	tsnState.stdin = s == "1"
	tsnState.tier, _ = tsnEnv("TEST_SAFETY_NET_GO_TIER")
	mods, _ := tsnEnv("TEST_SAFETY_NET_GO_MODULES")
	tsnState.modules = tsnSplit(mods)
	tsnState.armed = true
}

func tsnPkgOf(fn string) string {
	for i := 0; i < len(fn); i++ {
		if fn[i] == '[' {
			fn = fn[:i]
			break
		}
	}
	slash := -1
	for i := 0; i < len(fn); i++ {
		if fn[i] == '/' {
			slash = i
		}
	}
	for i := slash + 1; i < len(fn); i++ {
		if fn[i] == '.' {
			return fn[:i]
		}
	}
	return fn
}

func tsnIsStd(p string) bool {
	lo, hi := 0, len(tsnStd)
	for lo < hi {
		m := (lo + hi) / 2
		if tsnStd[m] < p {
			lo = m + 1
		} else {
			hi = m
		}
	}
	return lo < len(tsnStd) && tsnStd[lo] == p
}

func tsnHasPrefix(s, p string) bool { return len(s) >= len(p) && s[:len(p)] == p }

func tsnHasSuffix(s, p string) bool { return len(s) >= len(p) && s[len(s)-len(p):] == p }

func tsnItoa(n int) string {
	if n == 0 {
		return "0"
	}
	neg := n < 0
	if neg {
		n = -n
	}
	var b [20]byte
	i := len(b)
	for n > 0 {
		i--
		b[i] = byte('0' + n%10)
		n /= 10
	}
	if neg {
		i--
		b[i] = '-'
	}
	return string(b[i:])
}

func tsnGroupsFor(group, entry string) []string {
	if c, ok := tsnControls[entry]; ok {
		return tsnSplit(c)
	}
	for _, eg := range tsnEntryGroups {
		if tsnHasPrefix(entry, eg[0]) {
			if eg[1] != group {
				return []string{eg[1], group}
			}
			break
		}
	}
	return []string{group}
}

// TSNHook decides one call to a hooked standard-library function.
func TSNHook(group, target string) {
	tsnState.once.Do(tsnArm)
	if !tsnState.armed {
		return
	}
	frames := tsnFrames(group, target)
	entry, control, runner := "", "", false
	for i, f := range frames {
		if f.Function == "" {
			continue
		}
		pkg := tsnPkgOf(f.Function)
		if tsnIsStd(pkg) {
			entry = f.Function
			if pkg == "testing" {
				if c, ok := tsnControls[f.Function]; ok {
					control = c
				} else {
					runner = true
				}
			}
			continue
		}
		if pkg == "main" && tsnHasSuffix(f.File, "_testmain.go") {
			return
		}
		if control == "" && runner {
			return
		}
		tsnJudge(group, target, entry, control, f, frames[i+1:])
		return
	}
	// No attributable frame on this goroutine's stack. That used to EXEMPT the
	// call, and `go http.ListenAndServe(...)` in a unit bound a real port under
	// a GREEN proof: the compiler's wrapper for a `go` statement is hidden from
	// runtime.Callers, so such a goroutine's stack is ALL stdlib. It is judged
	// by the function that CREATED it instead.
	if runner || control != "" {
		return
	}
	if creator, ok := tsnCreator(); ok {
		tsnJudge(group, target, entry, "", creator, nil)
	}
}

// tsnFrames is the WHOLE stack above the hook, never a truncated one. A fixed
// buffer that filled up read its cut-off tail as "end of stack" and exempted
// the call: a 40-level recursive template read the environment under a GREEN
// proof. Past a million frames it fails closed rather than guess.
func tsnFrames(group, target string) []runtime.Frame {
	pcs := make([]uintptr, 64)
	n := runtime.Callers(3, pcs)
	for n == len(pcs) {
		if len(pcs) >= 1<<20 {
			tsnViolate(group, target, runtime.Frame{Function: "(a stack too deep to attribute)"}, false)
		}
		pcs = make([]uintptr, len(pcs)*4)
		n = runtime.Callers(3, pcs)
	}
	var out []runtime.Frame
	it := runtime.CallersFrames(pcs[:n])
	for {
		f, more := it.Next()
		out = append(out, f)
		if !more {
			return out
		}
	}
}

// tsnCreator is the function that started this goroutine, read from the
// "created by" line runtime.Stack appends, when it is not the standard
// library's or the generated test main's. A goroutine the runtime or a stdlib
// server started for itself has a stdlib creator and stays exempt.
func tsnCreator() (runtime.Frame, bool) {
	buf := make([]byte, 8192)
	n := runtime.Stack(buf, false)
	for n == len(buf) && len(buf) < 1<<24 {
		buf = make([]byte, len(buf)*4)
		n = runtime.Stack(buf, false)
	}
	s := string(buf[:n])
	i := tsnLastIndex(s, "\ncreated by ")
	if i < 0 {
		return runtime.Frame{}, false
	}
	rest := s[i+len("\ncreated by "):]
	fn, loc := rest, ""
	if j := tsnIndex(rest, "\n"); j >= 0 {
		fn, loc = rest[:j], rest[j+1:]
	}
	if j := tsnIndex(fn, " in goroutine"); j >= 0 {
		fn = fn[:j]
	}
	for len(loc) > 0 && (loc[0] == '\t' || loc[0] == ' ') {
		loc = loc[1:]
	}
	if j := tsnIndex(loc, " "); j >= 0 {
		loc = loc[:j]
	}
	if j := tsnIndex(loc, "\n"); j >= 0 {
		loc = loc[:j]
	}
	file, line := loc, 0
	if j := tsnLastIndex(loc, ":"); j >= 0 {
		file, line = loc[:j], tsnAtoi(loc[j+1:])
	}
	if fn == "" || tsnIsStd(tsnPkgOf(fn)) || tsnHasSuffix(file, "_testmain.go") {
		return runtime.Frame{}, false
	}
	return runtime.Frame{Function: fn, File: file, Line: line}, true
}

func tsnJudge(group, target, entry, control string, f runtime.Frame, rest []runtime.Frame) {
	groups := tsnGroupsFor(group, entry)
	if control != "" {
		groups = tsnSplit(control)
	}
	dep := tsnDependencyInit(f, rest)
	for _, g := range groups {
		if g == "stdin" {
			if tsnState.stdin {
				tsnViolate(g, target, f, dep)
			}
		} else if tsnState.blocked[g] {
			tsnViolate(g, target, f, dep)
		}
	}
}

// tsnDependencyInit: the attributable frame belongs to NO module under test,
// and the stack beneath it is package initialisation. The whole binary runs
// guarded, so a dependency whose initializer reads the environment trips every
// tier-1 unit in any package importing it -- the right verdict, but not one
// about the unit, and the message has to say so.
func tsnDependencyInit(f runtime.Frame, rest []runtime.Frame) bool {
	if len(tsnState.modules) == 0 {
		return false
	}
	pkg := tsnPkgOf(f.Function)
	for _, m := range tsnState.modules {
		if pkg == m || tsnHasPrefix(pkg, m+"/") {
			return false
		}
	}
	for _, r := range rest {
		if tsnHasPrefix(r.Function, "runtime.doInit") {
			return true
		}
	}
	return false
}

func tsnViolate(group, target string, f runtime.Frame, dep bool) {
	at := " (" + f.File + ":" + tsnItoa(f.Line) + ")"
	where := " from " + f.Function + at
	what := ". This is a CLASSIFICATION failure, not an assertion failure: reclassify the unit" +
		" to Tier 3 and discard the test, regardless of red or green"
	if dep {
		where = " during the initialisation of dependency " + tsnPkgOf(f.Function) + at
		what = ". That is the dependency's import-time work, not the unit's: nothing in a" +
			" package importing it can be proved at tier " + tsnState.tier + ". Reclassify the" +
			" unit to Tier 3, discard the test, and name the dependency in the report"
	}
	msg := "\nIOGuardViolation: a tier " + tsnState.tier + " candidate reached " + group +
		" I/O via " + target + where + what + " (references/stacks.md, \"Go row, in detail\").\n"
	Write(2, []byte(msg))
	Exit(3)
}

func tsnIndex(s, sub string) int {
	for i := 0; i+len(sub) <= len(s); i++ {
		if s[i:i+len(sub)] == sub {
			return i
		}
	}
	return -1
}

func tsnLastIndex(s, sub string) int {
	for i := len(s) - len(sub); i >= 0; i-- {
		if s[i:i+len(sub)] == sub {
			return i
		}
	}
	return -1
}

func tsnAtoi(s string) int {
	n := 0
	for i := 0; i < len(s) && s[i] >= '0' && s[i] <= '9'; i++ {
		n = n*10 + int(s[i]-'0')
	}
	return n
}

func tsnHook(group, target string) { TSNHook(group, target) }
'''

_FORWARDER = '''// Code generated by test-safety-net io_guard_go.py for one proof run. DO NOT EDIT.

package %s

import "syscall"

func tsnHook(group, target string) { syscall.TSNHook(group, target) }
'''


def _go_str(s):
    return json.dumps(s)


def _engine_source(std):
    return (_ENGINE
            .replace("__STD__", ", ".join(_go_str(p) for p in sorted(std)))
            .replace("__ENTRY__", ", ".join("{%s, %s}" % (_go_str(p), _go_str(g))
                                            for p, g in ENTRY_GROUPS))
            .replace("__CONTROLS__", ", ".join("%s: %s" % (_go_str(k), _go_str(v))
                                               for k, v in sorted(TESTING_CONTROLS.items()))))


# ── Building the overlay ─────────────────────────────────────────────────

def _go(go, args, env, cwd=None):
    proc = subprocess.run([go, *args], env=env, cwd=cwd, capture_output=True, text=True,
                          timeout=300, stdin=subprocess.DEVNULL)
    return proc.returncode, proc.stdout, proc.stderr


def _list_packages(go, env, pkgs):
    """path -> {"Dir", "GoFiles", "Name"} for each package this toolchain has."""
    code, out, err = _go(go, ["list", "-e", "-json", *pkgs], env)
    if code != 0 and not out.strip():
        raise GuardCannotArm("`go list` failed: %s" % (err.strip().splitlines() or ["?"])[-1])
    decoder, i, found = json.JSONDecoder(), 0, {}
    out = out.strip()
    while i < len(out):
        obj, end = decoder.raw_decode(out, i)
        i = end
        while i < len(out) and out[i].isspace():
            i += 1
        if obj.get("Error") or not obj.get("GoFiles"):
            continue
        found[obj["ImportPath"]] = obj
    return found


def build_overlay(go, env, dest):
    """(overlay JSON path, report) for this toolchain. Raises GuardCannotArm."""
    pkgs = sorted({p for p, _r, _n, _g in HOOK_TARGETS})
    listing = _list_packages(go, env, pkgs)
    code, std_out, err = _go(go, ["list", "std"], env)
    std = [line.strip() for line in std_out.splitlines() if line.strip()]
    if code != 0 or "syscall" not in std:
        raise GuardCannotArm("`go list std` failed: %s" % (err.strip() or "no output"))

    sources, hooked_pkgs = {}, set()
    report = {"hooked": [], "skipped": []}
    for pkg, recv, name, group in HOOK_TARGETS:
        label = "%s.%s" % (pkg, name if recv is None else "(*%s).%s" % (recv, name))
        required = (pkg, recv, name) in REQUIRED_TARGETS
        info = listing.get(pkg)
        if info is None:
            if required:
                raise GuardCannotArm("package %s is not in this toolchain" % pkg)
            report["skipped"].append((label, "package not in this toolchain"))
            continue
        if group == "stdin":
            stmt = 'if fd == 0 { tsnHook("stdin", "%s(0)") }' % label
        else:
            stmt = 'tsnHook("%s", "%s")' % (group, label)
        done = False
        for fname in info["GoFiles"]:
            path = os.path.join(info["Dir"], fname)
            if path not in sources:
                with open(path, encoding="utf-8") as f:
                    sources[path] = f.read()
            if group == "stdin" and not re.search(r"(?m)^func %s\(fd int," % name, sources[path]):
                continue
            try:
                new = inject(sources[path], name, stmt, recv)
            except KeyError:
                continue
            done = True
            if new is None:
                if required:
                    raise GuardCannotArm("%s has no Go body in this toolchain" % label)
                report["skipped"].append((label, "no Go body"))
            else:
                sources[path] = new
                hooked_pkgs.add(pkg)
                report["hooked"].append(label)
            break
        if not done:
            if required:
                raise GuardCannotArm("required hook target %s not found in this toolchain's "
                                     "sources" % label)
            report["skipped"].append((label, "not found in this toolchain"))
    if "syscall" not in hooked_pkgs:
        raise GuardCannotArm("no syscall function could be hooked")

    replace = {}
    for n, (path, text) in enumerate(sorted(sources.items())):
        if not any(path.startswith(os.path.join(listing[p]["Dir"], "")) for p in hooked_pkgs):
            continue
        out_path = os.path.join(dest, "%03d_%s" % (n, os.path.basename(path)))
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(text)
        replace[path] = out_path
    for pkg in sorted(hooked_pkgs):
        info = listing[pkg]
        text = (_engine_source(std) if pkg == "syscall"
                else _FORWARDER % info.get("Name", os.path.basename(pkg)))
        out_path = os.path.join(dest, "zz_tsn_%s.go" % pkg.replace("/", "_"))
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(text)
        replace[os.path.join(info["Dir"], "zz_tsn_hook.go")] = out_path
    overlay = os.path.join(dest, "overlay.json")
    with open(overlay, "w", encoding="utf-8") as f:
        json.dump({"Replace": replace}, f)
    return overlay, report


# ── Running ──────────────────────────────────────────────────────────────

def _asks_for_overlay(args):
    return any(a == "-overlay" or a.startswith("-overlay=") or a == "--overlay"
               or a.startswith("--overlay=") for a in args)


def _say(msg):
    sys.stderr.write(_PREFIX + msg + "\n")
    sys.stderr.flush()


def _not_armed(why):
    _say("NOT ARMED (exit 2): %s. Nothing was proved; fix the environment and re-run." % why)
    return EXIT_NOT_ARMED


def classify(code, out, overlay_dir):
    """The exit status for one `go test -v` run, from its code and its output.

    GREEN needs positive evidence: a `--- PASS:` line and no `--- SKIP:` one.
    It used to be "exit 0 and no `no tests to run`", and review found two more
    ways for `go test` to exit 0 having proved nothing -- a package with no
    `_test.go` files (`? pkg [no test files]`) and a test that calls `t.Skip`.
    Both read as GREEN, and a pinned test that skips itself would have been
    kept. Requiring the PASS line also stops a `./...` run whose other package
    printed `[no tests to run]` from reading as NO TEST.
    """
    if "IOGuardViolation" in out:
        return EXIT_TRIP
    if overlay_dir and (overlay_dir in out or "zz_tsn_" in out) and code != 0:
        return EXIT_NOT_ARMED
    if "[build failed]" in out or "[setup failed]" in out:
        return EXIT_NO_BUILD
    if code != 0:
        return EXIT_RED
    if "--- SKIP:" in out or "--- PASS:" not in out:
        return EXIT_NO_TEST
    return EXIT_GREEN


def _strip_count(args):
    """`args` without any `-count` -- both `-count=N` and the split `-count N`."""
    out, skip = [], False
    for a in args:
        if skip:
            skip = False
            continue
        if a in ("-count", "--count"):
            skip = True
            continue
        if a.startswith(("-count=", "--count=")):
            continue
        out.append(a)
    return out


def _main_modules(go, env):
    """The module path(s) under test, for telling the repo's code from a dependency's."""
    code, out, _err = _go(go, ["list", "-m", "-f", "{{.Path}}"], env, cwd=os.getcwd())
    return [line.strip() for line in out.splitlines() if line.strip()] if code == 0 else []


_OUTCOME = {
    EXIT_GREEN: "GREEN (exit 0): the selected test ran and passed",
    EXIT_RED: "RED (exit 1): the selected test ran and failed",
    EXIT_NOT_ARMED: "NOT ARMED (exit 2): the guard's overlay did not build on this "
                    "toolchain; nothing was proved",
    EXIT_TRIP: "GUARD TRIP (exit 3): the unit reached real I/O -- the CLASSIFICATION is "
               "wrong: reclassify it to Tier 3 and discard the test, red or green",
    EXIT_NO_TEST: "NO TEST (exit 4): nothing was proved -- -run matched no test, the "
                  "package has no test files, or the test skipped itself",
    EXIT_NO_BUILD: "NO BUILD (exit 5): the package did not build; a compile error is not RED",
}


def main(argv=None):
    argv = list(sys.argv[1:] if argv is None else argv)
    tier, allow, notes = read_env(os.environ)
    for note in notes:
        _say("note: " + note)
    go = shutil.which("go")
    if not go:
        return _not_armed("no `go` on PATH")
    if _asks_for_overlay(argv) or "overlay" in os.environ.get("GOFLAGS", ""):
        return _not_armed("the run already asks for -overlay, and a second overlay would "
                          "replace this guard's")
    env = dict(os.environ, GOTOOLCHAIN="local")
    code, out, err = _go(go, ["env", "-json", "GOOS", "GOARCH", "GOROOT", "GOVERSION"], env)
    try:
        info = json.loads(out)
    except ValueError:
        return _not_armed("`go env` failed: %s" % err.strip())
    if info.get("GOOS") not in SUPPORTED_GOOS:
        return _not_armed("GOOS=%s; this guard is proved on %s only"
                          % (info.get("GOOS"), " and ".join(SUPPORTED_GOOS)))
    argv = _strip_count(argv)
    modules = _main_modules(go, env)
    tmp = tempfile.mkdtemp(prefix="tsn-go-overlay-")
    try:
        try:
            overlay, _report = build_overlay(go, env, tmp)
        except GuardCannotArm as exc:
            return _not_armed(str(exc))
        blocked = blocked_groups(tier, allow)
        run_env = dict(env, GOPROXY="off",
                       TEST_SAFETY_NET_GO_BLOCKED=",".join(sorted(blocked)),
                       TEST_SAFETY_NET_GO_STDIN="1" if tier == 1 else "0",
                       TEST_SAFETY_NET_GO_TIER=str(tier),
                       TEST_SAFETY_NET_GO_MODULES=",".join(modules))
        # -count=1 is LOAD-BEARING. The engine reads its configuration through
        # runtime_envs(), which go test's result cache cannot see, so without it
        # a pass recorded at one tier would be replayed as `(cached)` at another.
        # -vet=off: `go vet` on Go 1.22 and 1.23 does not honour an overlay's
        # ADDED files and failed every run there ("vet: open .../zz_tsn_hook.go:
        # no such file"). Vet is a lint, not part of a proof. -v: `classify`
        # needs the `--- PASS:` / `--- SKIP:` lines to call a run GREEN.
        proc = subprocess.Popen([go, "test", "-overlay", overlay, "-count=1", "-vet=off",
                                 "-v", *argv],
                                env=run_env, stdin=subprocess.DEVNULL,
                                stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
        captured = []
        for line in proc.stdout:
            sys.stdout.write(line)
            captured.append(line)
        sys.stdout.flush()
        code = proc.wait()
        outcome = classify(code, "".join(captured), tmp)
        _say(_OUTCOME[outcome])
        return outcome
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


if __name__ == "__main__":
    sys.exit(main())
